config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :topicclusters

  map.resources :usecaseclusters

  map.resources :vocabtypes, :has_many => [:vocabs]

  map.resources :usages

  map.resources :topics

  map.resources :usecases, :has_many => [:vocabs,:topics]

  map.resources :vocabs, :has_many => [:usecases]
  
  map.resources :home, :only => :index

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  map.root :controller => "home"
end

app/models/usecase.rb
class Usecase < ActiveRecord::Base
  has_and_belongs_to_many :topics
  has_many :vocabs, :through => :usages
  has_many :usages
  
end

app/controllers/usecases_controller.rb
class UsecasesController < ApplicationController
  # GET /usecases
  # GET /usecases.xml
  def index
    if params[:vocab_id] then
      @usecases = Vocab.find(params[:vocab_id]).usecases
      @table_title = "Usecases using the vocab: <i>#{Vocab.find(params[:vocab_id]).name}</i>"
    else
      @usecases = Usecase.all
      @table_title = "All Usecases"
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @usecases }
      format.rss
    end
  end

  # GET /usecases/1
  # GET /usecases/1.xml
  def show
    @usecase = Usecase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @usecase }
    end
  end

  # GET /usecases/new
  # GET /usecases/new.xml
  def new
    @usecase = Usecase.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @usecase }
    end
  end

  # GET /usecases/1/edit
  def edit
    @usecase = Usecase.find(params[:id])
  end

  # POST /usecases
  # POST /usecases.xml
  def create
    @usecase = Usecase.new(params[:usecase])

    respond_to do |format|
      if @usecase.save
        format.html { redirect_to(@usecase, :notice => 'Usecase was successfully created.') }
        format.xml  { render :xml => @usecase, :status => :created, :location => @usecase }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @usecase.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /usecases/1
  # PUT /usecases/1.xml
  def update
    @usecase = Usecase.find(params[:id])

    respond_to do |format|
      if @usecase.update_attributes(params[:usecase])
        format.html { redirect_to(@usecase, :notice => 'Usecase was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @usecase.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /usecases/1
  # DELETE /usecases/1.xml
  def destroy
    @usecase = Usecase.find(params[:id])
    @usecase.destroy

    respond_to do |format|
      format.html { redirect_to(usecases_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/usecases_helper.rb
module UsecasesHelper
end

app/views/usecases/_form.html.erb
<% form_for @usecase, :html => {:id => 'usecase_form'} do |usecase_form| %>
<%= usecase_form.error_messages %>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">General</a></li>
		<li><a href="#tabs-2">Topics</a></li>
		<li><a href="#tabs-3">Vocabularies</a></li>
		
	</ul>
	<div id="tabs-1">
		<table class="panel">
			<tr class="panel">
				<td class="panel-field-name">Name:</td>
				<td class="panel-field-value"><%= usecase_form.text_field :name %></td>
			</tr>
			<tr class="panel">
				<td class="panel-field-name">URL:</td>
				<td class="panel-field-value"><%= usecase_form.text_field :url %></td>
			</tr>
			<tr class="panel">
				<td class="panel-field-name">Goal:</td>
				<td class="panel-field-value"><%= usecase_form.text_area :goal %></td>
			</tr>
	  </table>
	</div>
	<div id="tabs-2">
		<div class="panel-field-value">
			<div>
			<%
				rowcount = 0
				Topic.all.each do |topic|
				if rowcount % 20 == 0 then
			%>
			 	</div><div style="float:left">
			<% end %>
				<%= check_box_tag "usecase[topic_ids][]", topic.id, @usecase.topics.include?(topic) %> <%= topic.name %>
				<br />
				<%
					rowcount += 1
					end 
				%>
			</div>
		</div>
		<div style="clear:both;"></div>
	</div>
	<div id="tabs-3">
		<div class="panel-field-value">
			<div>
			<%
				rowcount = 0
				Vocab.all.each do |vocab|
				if rowcount % 20 == 0 then
			%>
			 	</div><div style="float:left">
			<% end %>
				<%= check_box_tag "usecase[vocab_ids][]", vocab.id, @usecase.vocabs.include?(vocab) %> <%= vocab.name %>
				<br />
				<%
					rowcount += 1
					end 
				%>
			</div>
		</div>
		<div style="clear:both;"></div>
	</div>
</div>

<% end %>

app/views/usecases/edit.html.erb
<%= render :partial => "shared/menu_bar"%>

<h2>Editing Usecase: <span class="entity-title"><%= @usecase.name %></span></h2>

<%= render :partial => "form" %>

<div class="page-navigation">
	<a href="" onClick="document.getElementById('usecase_form').submit();return(false)" class="action-link">Save changes</a><%= link_to 'Abandon changes and go back', @usecase%>

</div>

app/views/usecases/index.html.erb
<%= auto_discovery_link_tag(:rss, "#{url_for(:action => 'index')}.rss") %>

<%= render :partial => "shared/menu_bar"%>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1"><%= @table_title %></a><a href="<%= "#{url_for(:action => params[:action])}.rss" %>"><%= image_tag "icons/feedicon.png" %></a></li>
	</ul>
	<div id="tabs-1">
		<table class="panel-grid">
			<thead>
				<tr>
					<th>Name</th>
					<th>Vocabs</th>
					<th>Topics</th>
					<th class="{sorter: false}">&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				<% @usecases.each do |usecase| %>
				  <tr>
				    <td><%= link_to usecase.name, usecase %></td>
						<td><%= link_to usecase.vocabs.size,"#{ActionController::Base.relative_url_root}/usecases/#{usecase.id}/vocabs/" %></td>
						<td><%= link_to usecase.topics.size,"#{ActionController::Base.relative_url_root}/usecases/#{usecase.id}/topics/" %></td>
				    <td class="panel-grid-operations"><%= link_to 'Edit', edit_usecase_path(usecase) %> | <%= link_to 'Destroy', usecase, :confirm => 'Are you sure?', :method => :delete %></td>
				  </tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<br />

<%= link_to 'New usecase', new_usecase_path %>

app/views/usecases/new.html.erb
<%= render :partial => "shared/menu_bar"%>

<h2>Create Usecase</h2>

<%= render :partial => "form" %>

<div class="page-navigation">
	<a href="" onClick="document.getElementById('usecase_form').submit();return(false)" class="action-link">Save changes</a><%= link_to 'Abandon changes and go back', @usecase%>

app/views/usecases/show.html.erb
<%= render :partial => "shared/menu_bar"%>
<h2>Showing Use case: <span class="entity-title"><%= @usecase.name %></span></h2>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1">General</a></li>
	</ul>
	<div id="tabs-1">
		<table class="panel">
			<tr class="panel">
				<td class="panel-field-name">Name:</td>
				<td class="panel-field-value"><%=@usecase.name %></td>
			</tr>
			<tr class="panel">
				<td class="panel-field-name">URL:</td>
				<td class="panel-field-value"><%=@usecase.url %></td>
			</tr>
			<tr class="panel">
				<td class="panel-field-name">Goal:</td>
				<td class="panel-field-value"><%=@usecase.goal %></td>
			</tr>
			<tr class="panel">
				<td class="panel-field-name">Vocabs:</td>
				<td class="panel-field-value">
					<% @usecase.vocabs.each do |vocab| %>
						<%= link_to vocab.name,vocab %><br />
					<% end %>
					
				</td>
			</tr>
			<tr class="panel">
				<td class="panel-field-name">Topics:</td>
				<td class="panel-field-value">
					<% @usecase.topics.each do |topic| %>
						<%= link_to topic.name,topic %><br />
					<% end %>
					
				</td>
			</tr>
		</table>
	</div>		
</div>
<div class="page-navigation">
	<%= link_to 'Edit', edit_usecase_path(@usecase),:class => "action-link" %> |
	<%= link_to 'Back', usecases_path %>
</div>